import { StyleSheet } from 'react-native';
import {
  BG, CARD, BLUE, NAVY, TEXT, MUTED, BORDER, AMBER, RED,
} from './directorColors';

export const s = StyleSheet.create({
  center:      { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingTop: 60 },
  emptyText:   { fontSize: 14, color: MUTED },
  tabBar:      { flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1 },
  tabBtn:      { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabText:     { fontSize: 13, fontWeight: '600' },

  drpContainer: { backgroundColor: '#fff', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: BORDER },
  drpRow:       { flexDirection: 'row', gap: 8 },
  drpChip:      { flex: 1, paddingVertical: 7, borderRadius: 10, backgroundColor: BG, alignItems: 'center', borderWidth: 1, borderColor: BORDER },
  drpChipActive:{ backgroundColor: BLUE, borderColor: BLUE },
  drpChipText:  { fontSize: 12, fontWeight: '600', color: MUTED },
  drpChipTextActive: { color: '#fff' },
  drpCustomRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
  drpDateBtn:   { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: BG, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, borderWidth: 1, borderColor: BORDER },
  drpDateText:  { flex: 1, fontSize: 13, fontWeight: '500', color: TEXT },
  drpSep:       { fontSize: 14, color: MUTED, fontWeight: '600' },

  section:      { paddingHorizontal: 16, paddingTop: 16 },
  sectionHeader:{ flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  sectionTitle: { fontSize: 11, fontWeight: '700', color: MUTED, letterSpacing: 1.2 },

  card:  { backgroundColor: CARD, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: BORDER, gap: 0 },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: BORDER, marginVertical: 10 },

  statRow:  { flexDirection: 'row', gap: 8 },
  statCard: { flex: 1, alignItems: 'center', paddingVertical: 8 },
  statValue:{ fontSize: 18, fontWeight: '700', color: TEXT },
  statLabel:{ fontSize: 11, fontWeight: '500', color: MUTED, marginTop: 2, textAlign: 'center' },
  statSub:  { fontSize: 10, color: MUTED, textAlign: 'center', marginTop: 1 },

  hBarTrack:{ height: 6, backgroundColor: BORDER, borderRadius: 3, overflow: 'hidden' },
  hBarFill: { height: '100%', borderRadius: 3 },

  breakRow:  { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 6 },
  breakLabel:{ fontSize: 13, fontWeight: '600', color: TEXT },
  breakSub:  { fontSize: 11, color: MUTED },
  breakCount:{ fontSize: 12, fontWeight: '600', color: MUTED },
  breakValue:{ fontSize: 13, fontWeight: '700', color: NAVY, minWidth: 70, textAlign: 'right' },

  peakBanner:{ flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: AMBER + '15', borderRadius: 10, padding: 10, marginBottom: 12 },
  peakText:  { fontSize: 13, color: TEXT, flex: 1 },
  heatmapGrid:{ flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  heatCell:  { width: '12%', alignItems: 'center', gap: 3 },
  heatBlock: { width: '100%', aspectRatio: 1, borderRadius: 6, alignItems: 'center', justifyContent: 'center' },
  heatCount: { fontSize: 10, fontWeight: '700' },
  heatLabel: { fontSize: 8, color: MUTED, textAlign: 'center' },

  emptyState:{ alignItems: 'center', justifyContent: 'center', paddingVertical: 24, gap: 8 },
  sectionLoader:{ paddingVertical: 32, alignItems: 'center' },

  fbHeader:  { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8, flexWrap: 'wrap' },
  fbDate:    { fontSize: 11, color: MUTED, marginLeft: 'auto' as any },
  fbMessage: { fontSize: 13, color: TEXT, lineHeight: 19 },
  pill:      { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 20 },
  pillText:  { fontSize: 10, fontWeight: '700' },

  filterInput: {
    backgroundColor: BG, borderWidth: 1, borderColor: BORDER, borderRadius: 12,
    paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, color: TEXT, marginBottom: 12,
  },
  filterLabel: { fontSize: 11, fontWeight: '700', color: MUTED, letterSpacing: 0.8, marginBottom: 8 },
  filterChipRow: { gap: 8, paddingRight: 4, marginBottom: 12 },
  filterChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: BORDER, backgroundColor: BG },
  filterChipActive: { backgroundColor: BLUE, borderColor: BLUE },
  filterChipText: { fontSize: 12, fontWeight: '600', color: MUTED },
  filterChipTextActive: { color: '#fff' },
  registerReportHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 12 },
  statusPill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1 },
  statusPillManual: { backgroundColor: '#ECFDF5', borderColor: '#BBF7D0' },
  statusPillAuto: { backgroundColor: '#EFF6FF', borderColor: '#BFDBFE' },
  statusPillEmpty: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, borderWidth: 1, backgroundColor: '#F5F5F5', borderColor: '#D1D5DB' },
  statusPillText: { fontSize: 11, fontWeight: '700' },
  statusPillTextManual: { color: '#15803D' },
  statusPillTextAuto: { color: BLUE },
  statusPillTextEmpty: { fontSize: 11, fontWeight: '600', color: MUTED },
  registerRevRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#EFF6FF', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10,
    marginBottom: 10, borderWidth: 1, borderColor: '#BFDBFE',
  },
  registerRevLabel: { fontSize: 10, fontWeight: '800', color: BLUE, letterSpacing: 1, marginBottom: 2 },
  registerRevValue: { fontSize: 20, fontWeight: '800', color: BLUE },
  registerRevBreakdown: { alignItems: 'flex-end', gap: 2 },
  registerRevBreakdownItem: { fontSize: 12, fontWeight: '700', color: TEXT },
  registerRevBreakdownDim: { fontSize: 12, fontWeight: '500', color: MUTED },
  registerReportGrid: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  registerMetricBox: { flex: 1, backgroundColor: '#F8FAFC', borderRadius: 12, borderWidth: 1, borderColor: BORDER, padding: 10 },
  registerMetricBoxLabel: { fontSize: 10, fontWeight: '700', color: MUTED, marginBottom: 4, letterSpacing: 0.6 },
  registerMetricBoxValue: { fontSize: 13, fontWeight: '700', color: TEXT },
  registerMetaRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  notesInput: {
    minHeight: 92, borderRadius: 12, borderWidth: 1, borderColor: BORDER, backgroundColor: BG,
    paddingHorizontal: 12, paddingVertical: 12, fontSize: 14, color: TEXT,
    textAlignVertical: 'top', marginBottom: 12,
  },
  detailActionRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  secondaryActionBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: '#BFDBFE', backgroundColor: '#EFF6FF',
  },
  secondaryActionText: { fontSize: 14, fontWeight: '700', color: BLUE },
  primaryActionBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    paddingVertical: 13, borderRadius: 12, backgroundColor: NAVY,
  },
  primaryActionText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  downloadBtn:     { margin: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: NAVY, paddingVertical: 14, borderRadius: 14 },
  downloadBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});

export const dl = StyleSheet.create({
  container:    { flex: 1, backgroundColor: '#FAFAFA' },
  header:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, borderBottomWidth: 1, borderBottomColor: BORDER },
  headerLeft:   { flexDirection: 'row', alignItems: 'center', gap: 12 },
  iconBox:      { width: 40, height: 40, borderRadius: 12, backgroundColor: BLUE + '15', alignItems: 'center', justifyContent: 'center' },
  title:        { fontSize: 17, fontWeight: '700', color: TEXT },
  subtitle:     { fontSize: 12, color: MUTED, marginTop: 1 },
  closeBtn:     { width: 36, height: 36, borderRadius: 18, backgroundColor: BORDER, alignItems: 'center', justifyContent: 'center' },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: MUTED, letterSpacing: 1.2 },
  preset:       { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10, backgroundColor: BG, borderWidth: 1, borderColor: BORDER },
  presetActive: { backgroundColor: BLUE, borderColor: BLUE },
  presetText:   { fontSize: 13, fontWeight: '600', color: TEXT },
  dateRow:      { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dateLabel:    { fontSize: 13, fontWeight: '600', color: MUTED, width: 36 },
  dateInputWrap:{ flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: BORDER, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  dateInput:    { flex: 1, fontSize: 14, color: TEXT },
  dateParsed:   { fontSize: 12, color: MUTED },
  footer:       { flexDirection: 'row', gap: 12, padding: 20, borderTopWidth: 1 },
  cancelBtn:    { flex: 1, paddingVertical: 14, borderRadius: 12, backgroundColor: BORDER, alignItems: 'center' },
  cancelText:   { fontSize: 15, fontWeight: '600', color: TEXT },
  downloadBtn:  { flex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 12, backgroundColor: BLUE },
  downloadText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});
