import { StyleSheet } from 'react-native';
import { BG, WHITE, BLUE, CHERRY, DARK, MID, MUTED, BORDER, TICKET } from './types';

const REORDER_ITEM_H = 58;

const styles = StyleSheet.create({
  root:               { flex: 1, backgroundColor: BG },
  header:             { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: WHITE, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  headerTitle:        { fontSize: 18, fontWeight: '700', color: DARK },
  headerBtn:          { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#F1F5F9', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  headerSyncTime:     { fontSize: 9, color: MUTED, lineHeight: 11, marginTop: 1 },
  headerBtnText:      { fontSize: 12, fontWeight: '600', color: MID },

  salesStrip:         { flexDirection: 'row', backgroundColor: '#EFF6FF', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingHorizontal: 16, paddingVertical: 10, gap: 20 },
  salesCard:          { flexDirection: 'row', alignItems: 'center', gap: 8 },
  salesLabel:         { fontSize: 12, color: MUTED, fontWeight: '500' },
  salesValue:         { fontSize: 16, fontWeight: '700', color: DARK, marginLeft: 4 },

  holdTabsRow:        { backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingHorizontal: 12, paddingVertical: 8, flexGrow: 0 },
  holdTab:            { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#F1F5F9', marginRight: 6 },
  holdTabActive:      { backgroundColor: BLUE },
  holdTabText:        { fontSize: 13, fontWeight: '600', color: MID },
  holdTabAdd:         { width: 32, height: 32, borderRadius: 16, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center', alignSelf: 'center' },

  paneTabBar:         { flexDirection: 'row', backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  paneTab:            { flex: 1, paddingVertical: 10, alignItems: 'center' },
  paneTabActive:      { borderBottomWidth: 2, borderBottomColor: BLUE },
  paneTabText:        { fontSize: 14, fontWeight: '600', color: MUTED },
  paneTabTextActive:  { color: BLUE },
  paneTabBadge:       { marginTop: 2, backgroundColor: '#EFF6FF', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  paneTabBadgeText:   { fontSize: 11, fontWeight: '700', color: BLUE },

  body:               { flex: 1, flexDirection: 'row' },
  menuPane:           { flex: 1, backgroundColor: BG },
  ticketPane:         { backgroundColor: TICKET, borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: BORDER },

  searchRow:          { padding: 12, paddingBottom: 6 },
  searchInputWrap:    { flexDirection: 'row', alignItems: 'center', backgroundColor: WHITE, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: BORDER },
  searchInput:        { flex: 1, fontSize: 15, color: DARK },
  categoryScrollWrap: { height: 84, flexShrink: 0 },
  categoryScroll: { flex: 1 },
  catTile:        { width: 72, height: 68, borderRadius: 12, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  catTileLabel:   { fontSize: 12, fontWeight: '700', textAlign: 'center', lineHeight: 16 },

  productCard:        { backgroundColor: WHITE, borderRadius: 10, overflow: 'hidden', margin: 0, borderWidth: StyleSheet.hairlineWidth, borderColor: BORDER },
  productCardImage:   { width: '100%', aspectRatio: 1.2, backgroundColor: '#F8FAFC' },
  productCardBody:    { padding: 8 },
  productCardName:    { fontSize: 13, fontWeight: '600', color: DARK, lineHeight: 17 },
  productCardPrice:   { fontSize: 14, fontWeight: '700', color: BLUE },
  productCardOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255,255,255,0.7)', justifyContent: 'center', alignItems: 'center' },
  variantBadge:       { backgroundColor: '#EFF6FF', borderRadius: 8, paddingHorizontal: 6, paddingVertical: 2 },
  variantBadgeText:   { fontSize: 10, color: BLUE, fontWeight: '600' },

  ticketContainer:    { flex: 1, display: 'flex', flexDirection: 'column' },
  customerBar:        { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingHorizontal: 14, paddingVertical: 12 },
  customerSection:    { backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 10 },
  customerBarInner:   { flexDirection: 'row', alignItems: 'center', gap: 8 },
  stampRow:           { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 8 },
  stampCircle:        { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, borderColor: BORDER, backgroundColor: WHITE, justifyContent: 'center', alignItems: 'center' },
  stampCircleFilled:  { backgroundColor: '#92400E', borderColor: '#92400E' },
  stampCircleNext:    { borderColor: BLUE, borderWidth: 2 },
  stampLabel:         { fontSize: 11, color: MUTED, marginLeft: 'auto' as any },
  customerName:       { fontSize: 14, fontWeight: '700', color: DARK },
  customerSub:        { fontSize: 12, color: MUTED, marginTop: 1 },
  customerPlaceholder: { fontSize: 14, color: MUTED },
  customerBtnRow:     { flexDirection: 'row', backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  customerBtn:        { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 11 },
  customerBtnText:    { fontSize: 13, fontWeight: '600', color: BLUE },
  customerBtnDivider: { width: StyleSheet.hairlineWidth, backgroundColor: BORDER, marginVertical: 8 },
  headerSearchRow:    { flexDirection: 'row', alignItems: 'center', backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingHorizontal: 14, paddingVertical: 9 },

  orderTypeRow:       { flexDirection: 'row', gap: 6, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  orderTypeChip:      { flex: 1, paddingVertical: 6, borderRadius: 8, backgroundColor: '#F1F5F9', alignItems: 'center' },
  orderTypeChipActive: { backgroundColor: BLUE },
  orderTypeText:      { fontSize: 12, fontWeight: '600', color: MID },
  orderTypeTextActive: { color: WHITE },

  emptyTicket:        { padding: 32, alignItems: 'center', gap: 12 },
  emptyTicketText:    { fontSize: 14, color: MUTED, textAlign: 'center', lineHeight: 20 },

  ticketItem:         { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, backgroundColor: WHITE, marginBottom: 1 },
  ticketItemName:     { fontSize: 14, fontWeight: '600', color: DARK },
  ticketItemMeta:     { fontSize: 12, color: MUTED, marginTop: 2 },
  ticketItemNotes:    { fontSize: 11, color: BLUE, marginTop: 2, fontStyle: 'italic' },
  ticketItemRight:    { alignItems: 'flex-end', gap: 6 },
  ticketItemPrice:    { fontSize: 14, fontWeight: '700', color: DARK },
  qtyControls:        { flexDirection: 'row', alignItems: 'center', gap: 8 },
  qtyBtn:             { width: 26, height: 26, borderRadius: 6, backgroundColor: '#F1F5F9', justifyContent: 'center', alignItems: 'center' },
  qtyText:            { fontSize: 14, fontWeight: '700', color: DARK, minWidth: 20, textAlign: 'center' },
  ticketSwipeDelete:      { backgroundColor: CHERRY, width: 80, justifyContent: 'center', alignItems: 'center', gap: 4 },
  ticketSwipeDeleteLabel: { color: '#FFFFFF', fontSize: 11, fontWeight: '600' },

  totalsSection:      { borderTopWidth: 1, borderTopColor: BORDER, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 4, backgroundColor: WHITE },
  totalRow:           { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  totalLabel:         { fontSize: 13, color: MID },
  totalValue:         { fontSize: 13, fontWeight: '600', color: DARK },
  totalRowFinal:      { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER },
  totalFinalLabel:    { fontSize: 16, fontWeight: '700', color: DARK },
  totalFinalValue:    { fontSize: 18, fontWeight: '800', color: DARK },

  ticketActions:      { padding: 12, backgroundColor: WHITE, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER },
  clearBtn:           { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 10, backgroundColor: '#FFF1F2', borderWidth: 1, borderColor: '#FECDD3' },
  clearBtnText:       { fontSize: 14, fontWeight: '600', color: CHERRY },
  holdBtn:            { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 10, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  holdBtnText:        { fontSize: 14, fontWeight: '600', color: MID },
  chargeBtn:          { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: CHERRY, borderRadius: 12, paddingVertical: 16 },
  chargeBtnText:      { fontSize: 18, fontWeight: '800', color: WHITE },

  customiseRoot:      { flex: 1, backgroundColor: WHITE },
  sheetHeader:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  sheetTitle:         { fontSize: 17, fontWeight: '700', color: DARK, flex: 1, textAlign: 'center' },
  sheetFooter:        { paddingHorizontal: 16, paddingVertical: 12, backgroundColor: WHITE, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, flexDirection: 'row', alignItems: 'center', gap: 16 },
  sheetPriceLabel:    { fontSize: 12, color: MUTED, fontWeight: '500' },
  sheetPrice:         { fontSize: 22, fontWeight: '800', color: DARK },
  addToOrderBtn:      { flex: 1, backgroundColor: CHERRY, borderRadius: 12, paddingVertical: 15, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  addToOrderBtnText:  { fontSize: 16, fontWeight: '800', color: WHITE },
  registerHero:       { backgroundColor: '#F8FAFC', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: BORDER, flexDirection: 'row', gap: 12, alignItems: 'center' },
  registerHeroTitle:  { fontSize: 18, fontWeight: '800', color: DARK },
  registerHeroSub:    { fontSize: 13, color: MID, marginTop: 2 },
  registerHeroMeta:   { fontSize: 12, color: MUTED, marginTop: 6 },
  registerStatusPill: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#E2E8F0' },
  registerStatusOpen: { backgroundColor: '#DCFCE7' },
  registerStatusNeedsFloat: { backgroundColor: '#FEE2E2' },
  registerStatusText: { fontSize: 12, fontWeight: '800', color: '#166534' },
  registerGrid:       { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  registerCard:       { width: '47.8%', backgroundColor: WHITE, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: BORDER },
  registerMetricLabel:{ fontSize: 12, color: MUTED, fontWeight: '600' },
  registerMetricValue:{ fontSize: 20, color: DARK, fontWeight: '800', marginTop: 6 },
  registerSection:    { backgroundColor: WHITE, borderRadius: 16, padding: 14, borderWidth: 1, borderColor: BORDER },
  regAccordionGroup:  { backgroundColor: WHITE, borderRadius: 16, borderWidth: 1, borderColor: BORDER, overflow: 'hidden' },
  regAccordionRow:    { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 14 },
  regAccordionIcon:   { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  regAccordionTitle:  { fontSize: 14, fontWeight: '700', color: DARK },
  regAccordionSub:    { fontSize: 12, color: MUTED, marginTop: 2 },
  regAccordionBody:   { paddingHorizontal: 14, paddingBottom: 16, paddingTop: 4, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, backgroundColor: '#FAFBFC' },
  regAccordionDivider:{ height: StyleSheet.hairlineWidth, backgroundColor: BORDER, marginLeft: 60 },
  regTabBar:          { flexDirection: 'row', backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  regTab:             { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  regTabActive:       { borderBottomColor: BLUE },
  regTabText:         { fontSize: 13, fontWeight: '600', color: MUTED },
  regTabTextActive:   { color: BLUE },
  regHeaderDrawerBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#FFF7ED', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#FDE68A' },
  regHeaderSideBtn:   { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  regDrawerAction:    { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FFFBEB', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#FDE68A' },
  regDrawerActionTitle: { fontSize: 15, fontWeight: '700', color: '#D97706' },
  regPastSessionsBtn: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: WHITE, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: BORDER },
  regPastSessionsBtnText: { flex: 1, fontSize: 14, fontWeight: '600', color: MID },
  regHistoryRow:      { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: WHITE, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: BORDER },
  regHistoryDate:     { fontSize: 14, fontWeight: '700', color: DARK },
  regHistoryMeta:     { fontSize: 12, color: MUTED, marginTop: 2 },
  regHistoryAmt:      { fontSize: 16, fontWeight: '800', color: DARK },
  registerLine:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 6 },
  registerLineLabel:  { fontSize: 13, color: MID, fontWeight: '600' },
  registerLineValue:  { fontSize: 14, color: DARK, fontWeight: '800' },
  registerInput:      { backgroundColor: '#F8FAFC', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, borderWidth: 1, borderColor: BORDER, fontSize: 14, color: DARK, marginBottom: 10 },
  registerTextarea:   { minHeight: 84, textAlignVertical: 'top' },
  registerToggleRow:  { flexDirection: 'row', gap: 8, marginBottom: 10 },
  registerToggleBtn:  { flex: 1, borderRadius: 10, borderWidth: 1, borderColor: BORDER, backgroundColor: '#F8FAFC', paddingVertical: 10, alignItems: 'center' },
  registerToggleBtnActive: { backgroundColor: BLUE, borderColor: BLUE },
  registerToggleText: { fontSize: 13, fontWeight: '700', color: MID },
  registerToggleTextActive: { color: WHITE },
  registerMovementRow:{ borderRadius: 10, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: BORDER, padding: 10 },
  registerMovementTitle: { fontSize: 13, fontWeight: '700', color: DARK },
  registerMovementMeta: { fontSize: 12, color: MUTED, marginTop: 3 },
  registerVarianceRow:{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  denomGrid:          { flexDirection: 'row', gap: 8, marginBottom: 10 },
  denomColumn:        { flex: 1, gap: 6 },
  denomColHeader:     { fontSize: 11, fontWeight: '700', color: MUTED, letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 2 },
  denomCell:          { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 9, paddingHorizontal: 10, backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: BORDER },
  denomCellLabel:     { width: 36, fontSize: 14, fontWeight: '700', color: DARK },
  denomCellBtn:       { width: 32, height: 32, borderRadius: 8, backgroundColor: WHITE, borderWidth: 1, borderColor: BORDER, alignItems: 'center', justifyContent: 'center' },
  denomCellInput:     { flex: 1, height: 34, borderWidth: 1, borderColor: BORDER, borderRadius: 8, backgroundColor: WHITE, textAlign: 'center', fontSize: 16, fontWeight: '700', color: DARK },
  denomSummaryRow:    { flexDirection: 'row', backgroundColor: '#F8FAFC', borderRadius: 10, padding: 10, borderWidth: 1, borderColor: BORDER, marginBottom: 6 },
  denomSummaryItem:   { flex: 1, alignItems: 'center', gap: 2 },
  denomSummarySep:    { width: 1, backgroundColor: BORDER, alignSelf: 'stretch', marginHorizontal: 4 },
  denomSummaryKey:    { fontSize: 11, color: MUTED, fontWeight: '600' },
  denomSummaryVal:    { fontSize: 14, fontWeight: '700', color: DARK },
  registerAutoRow:   { flexDirection: 'row', alignItems: 'center', gap: 12 },
  registerSwitch:    { width: 54, height: 30, borderRadius: 999, backgroundColor: '#CBD5E1', padding: 3, justifyContent: 'center' },
  registerSwitchOn:  { backgroundColor: BLUE },
  registerSwitchKnob:{ width: 24, height: 24, borderRadius: 12, backgroundColor: WHITE },
  registerSwitchKnobOn: { alignSelf: 'flex-end' },
  registerSecondaryBtn: { marginTop: 10, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 10, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE' },
  registerSecondaryBtnText: { fontSize: 13, fontWeight: '700', color: BLUE },

  section:            { marginBottom: 20 },
  sectionTitle:       { fontSize: 14, fontWeight: '700', color: DARK, marginBottom: 10 },
  sectionSubtitle:    { fontSize: 12, color: MUTED, marginTop: -6, marginBottom: 8 },
  requiredBadge:      { fontSize: 11, fontWeight: '700', color: CHERRY, backgroundColor: '#FFF1F2', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },

  variantChip:        { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 10, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  variantChipActive:  { backgroundColor: BLUE, borderColor: BLUE },
  variantChipText:    { fontSize: 13, fontWeight: '600', color: MID },

  optionPill:         { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 6, borderWidth: 1.5, borderColor: BORDER, backgroundColor: WHITE, gap: 2 },
  optionPillActive:   { backgroundColor: BLUE, borderColor: BLUE },
  optionPillLabel:    { fontSize: 13, color: DARK, fontWeight: '500' },
  optionPillSub:      { fontSize: 11, color: MUTED, fontWeight: '400' },

  quantityStepper:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 0, backgroundColor: '#F1F5F9', borderRadius: 12, alignSelf: 'flex-start' },
  stepperBtn:         { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
  stepperQty:         { fontSize: 20, fontWeight: '800', color: DARK, minWidth: 44, textAlign: 'center' },

  notesInput:         { backgroundColor: '#F8FAFC', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: BORDER, fontSize: 14, color: DARK, minHeight: 72, textAlignVertical: 'top' },

  payTotal:             { alignItems: 'center', paddingVertical: 20, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, marginBottom: 20 },
  payTotalLabel:        { fontSize: 14, color: MUTED, fontWeight: '500' },
  payTotalValue:        { fontSize: 40, fontWeight: '800', color: DARK, marginTop: 4 },
  payDiscountRow:       { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  payDiscountLabel:     { fontSize: 13, color: '#16A34A', fontWeight: '500', flex: 1 },
  payDiscountSaving:    { fontSize: 13, fontWeight: '700', color: '#16A34A' },
  payBreakdownBox:      { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: BORDER },
  payBreakdownRow:      { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  payBreakdownLabel:    { fontSize: 14, color: MID },
  payBreakdownValue:    { fontSize: 14, fontWeight: '600', color: DARK },
  methodRow:            { flexDirection: 'row', gap: 8, marginBottom: 10 },
  methodBtn:            { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 11, borderRadius: 12, backgroundColor: '#F1F5F9', borderWidth: 1.5, borderColor: BORDER },
  methodBtnActive:      { backgroundColor: BLUE, borderColor: BLUE },
  methodBtnText:        { fontSize: 14, fontWeight: '700', color: MID },
  eftposInstructions:   { alignItems: 'center', paddingVertical: 32, gap: 12 },
  eftposText:           { fontSize: 16, fontWeight: '600', color: DARK, textAlign: 'center' },
  eftposSubText:        { fontSize: 13, color: MUTED, textAlign: 'center' },
  presetBtn:            { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 10, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE' },
  presetBtnText:        { fontSize: 15, fontWeight: '700', color: BLUE },
  tenderedDisplay:      { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, alignItems: 'flex-end', marginBottom: 12, borderWidth: 1, borderColor: BORDER },
  tenderedText:         { fontSize: 36, fontWeight: '800', color: DARK },
  changeRow:            { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#ECFDF5', borderRadius: 10, padding: 12, marginBottom: 16 },
  changeLabel:          { fontSize: 15, fontWeight: '600', color: '#16A34A' },
  changeValue:          { fontSize: 15, fontWeight: '800', color: '#16A34A' },
  numpad:               { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignSelf: 'flex-start', width: 210 },
  numpadKey:            { width: 64, height: 46, backgroundColor: '#F1F5F9', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  numpadKeyText:        { fontSize: 20, fontWeight: '700', color: DARK, textAlignVertical: 'center' },
  tipOption:            { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14, borderRadius: 12, backgroundColor: '#F8FAFC', borderWidth: 1.5, borderColor: BORDER },
  tipOptionActive:      { backgroundColor: '#EFF6FF', borderColor: BLUE },
  tipOptionLabel:       { fontSize: 15, fontWeight: '600', color: DARK },
  tipOptionLabelActive: { color: BLUE },
  tipOptionAmount:      { fontSize: 15, fontWeight: '700', color: MID },
  tipOptionAmountActive:{ color: BLUE },
  splitAmountBox:       { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6, padding: 10, borderRadius: 10, borderWidth: 1 },
  surchargePreviewBox:  { backgroundColor: '#FFF7ED', borderRadius: 10, padding: 12, marginTop: 8, marginBottom: 8, borderWidth: 1, borderColor: '#FDBA74' },
  surchargePreviewTitle:{ fontSize: 12, fontWeight: '700', color: '#EA580C', marginBottom: 4 },
  surchargeLabel:       { fontSize: 13, color: '#92400E' },
  surchargeCentsText:   { fontSize: 13, fontWeight: '600', color: '#EA580C' },

  completeBg:         { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  completeCard:       { backgroundColor: WHITE, borderRadius: 20, padding: 28, alignItems: 'center', width: '100%', maxWidth: 380 },
  completeCheck:      { width: 64, height: 64, borderRadius: 32, backgroundColor: '#16A34A', justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  completeTitle:      { fontSize: 22, fontWeight: '800', color: DARK, marginBottom: 4 },
  completeOrder:      { fontSize: 14, color: MUTED, fontWeight: '600', marginBottom: 4 },
  completeTotal:      { fontSize: 34, fontWeight: '900', color: DARK, marginBottom: 12 },
  changeRowComplete:  { flexDirection: 'row', gap: 12, backgroundColor: '#ECFDF5', borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10, marginBottom: 16 },
  changeLabelComplete: { fontSize: 15, fontWeight: '600', color: '#16A34A' },
  changeValueComplete: { fontSize: 15, fontWeight: '800', color: '#16A34A' },
  loyaltyCard:        { backgroundColor: '#EFF6FF', borderRadius: 14, padding: 16, width: '100%', marginBottom: 20 },
  loyaltyDivider:     { width: 1, backgroundColor: '#BFDBFE', marginVertical: 4 },
  loyaltyStatLabel:   { fontSize: 12, color: MUTED, fontWeight: '500', marginBottom: 4 },
  loyaltyStatValue:   { fontSize: 24, fontWeight: '800', color: BLUE },
  loyaltyStatSub:     { fontSize: 11, color: MUTED, marginTop: 2 },
  rewardUnlocked:     { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, backgroundColor: '#ECFDF5', borderRadius: 10, padding: 10 },
  rewardUnlockedText: { fontSize: 14, fontWeight: '700', color: '#16A34A' },
  completeCloseBtn:   { backgroundColor: BLUE, borderRadius: 12, paddingVertical: 14, paddingHorizontal: 40, width: '100%', alignItems: 'center' },
  completeCloseBtnText: { fontSize: 16, fontWeight: '800', color: WHITE },

  currentCustomerCard: { margin: 12, backgroundColor: '#EFF6FF', borderRadius: 12, padding: 14, flexDirection: 'row', alignItems: 'center' },
  removeCustomerBtn:  { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: '#FFF1F2', borderWidth: 1, borderColor: '#FECDD3' },
  removeCustomerText: { fontSize: 13, fontWeight: '700', color: CHERRY },
  modeRow:            { flexDirection: 'row', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  modeBtn:            { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12 },
  modeBtnActive:      { borderBottomWidth: 2, borderBottomColor: BLUE },
  modeBtnText:        { fontSize: 14, fontWeight: '600', color: MID },
  customerResultRow:  { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  customerAvatar:     { width: 40, height: 40, borderRadius: 20, backgroundColor: BLUE, justifyContent: 'center', alignItems: 'center' },
  customerAvatarText: { fontSize: 18, fontWeight: '700', color: WHITE },

  historySummaryBar:      { flexDirection: 'row', backgroundColor: '#EFF6FF', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, paddingVertical: 12 },
  historySummaryItem:     { flex: 1, alignItems: 'center', gap: 2 },
  historySummaryLabel:    { fontSize: 11, fontWeight: '500', color: MUTED, textTransform: 'uppercase', letterSpacing: 0.5 },
  historySummaryValue:    { fontSize: 20, fontWeight: '800', color: DARK },
  historySummaryDivider:  { width: StyleSheet.hairlineWidth, backgroundColor: BORDER, marginVertical: 4 },

  historyRow:             { backgroundColor: WHITE, borderRadius: 12, marginBottom: 8, overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: BORDER },
  historyRowVoided:       { opacity: 0.65 },
  historyRowHeader:       { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12 },
  historyOrderNum:        { fontSize: 15, fontWeight: '700', color: DARK },
  historyStatusBadge:     { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2 },
  historyStatusText:      { fontSize: 11, fontWeight: '700' },
  historyMeta:            { fontSize: 12, color: MUTED },
  historyMetaDot:         { fontSize: 12, color: MUTED },
  historyTotal:           { fontSize: 17, fontWeight: '800', color: DARK },
  historyPayMethod:       { fontSize: 12, color: MUTED, fontWeight: '500' },

  historyItemsSection:    { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#FAFBFF', gap: 6 },
  historyLineItem:        { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  historyLineQty:         { fontSize: 13, fontWeight: '700', color: MUTED, minWidth: 24 },
  historyLineName:        { fontSize: 13, color: DARK, fontWeight: '500', flex: 1 },
  historyLineNote:        { fontSize: 11, color: BLUE, fontStyle: 'italic', marginTop: 1 },
  historyLinePrice:       { fontSize: 13, fontWeight: '700', color: DARK },
  historyOrderNote:       { fontSize: 12, color: MID, fontStyle: 'italic', marginTop: 4, paddingTop: 6, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER },

  historyVoidRow:         { marginTop: 10, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  historyVoidBtn:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: CHERRY, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12 },
  historyVoidBtnText:     { fontSize: 13, fontWeight: '700', color: WHITE },
  historyVoidExpired:     { fontSize: 12, color: MUTED, fontStyle: 'italic', flex: 1 },
  historyReprintBtn:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#EFF6FF', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#BFDBFE' },
  historyReprintBtnText:  { fontSize: 13, fontWeight: '700', color: BLUE },
  historyRefundBtn:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#92400E', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12 },
  historyRefundBtnText:   { fontSize: 13, fontWeight: '700', color: WHITE },
  loadMoreBtn:            { alignItems: 'center', justifyContent: 'center', paddingVertical: 14, marginHorizontal: 16, marginBottom: 8, marginTop: 4, borderRadius: 10, borderWidth: 1, borderColor: BORDER, backgroundColor: WHITE },
  loadMoreText:           { fontSize: 14, fontWeight: '600', color: BLUE },

  historyFilterRow:         { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  historyFilterChip:        { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  historyFilterChipActive:  { backgroundColor: BLUE, borderColor: BLUE },
  historyFilterChipText:    { fontSize: 13, fontWeight: '600', color: MID },
  historyFilterChipTextActive: { color: WHITE },
  historyFilterCount:       { minWidth: 18, height: 18, borderRadius: 9, backgroundColor: BORDER, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  historyFilterCountActive: { backgroundColor: 'rgba(255,255,255,0.3)' },
  historyFilterCountText:   { fontSize: 10, fontWeight: '700', color: MID },
  historyFilterCountTextActive: { color: WHITE },

  discountSection:      { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, paddingHorizontal: 12, paddingVertical: 8 },
  discountChips:        { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  discountChip:         { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  discountChipCode:     { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE' },
  discountChipCoffee:   { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#ECFDF5', borderWidth: 1, borderColor: '#A7F3D0' },
  discountChipReward:   { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#FFF7ED', borderWidth: 1, borderColor: '#FED7AA' },
  discountChipText:     { fontSize: 13, fontWeight: '700', color: MID },
  discountApplied:      { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#ECFDF5', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: '#A7F3D0' },
  discountAppliedText:  { fontSize: 13, fontWeight: '600', color: '#16A34A', flex: 1 },
  discountCodeRow:      { flexDirection: 'row', gap: 8, marginTop: 8 },
  discountCodeInput:    { flex: 1, backgroundColor: WHITE, borderRadius: 8, borderWidth: 1, borderColor: BORDER, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, fontWeight: '700', color: DARK },
  discountCodeApplyBtn: { backgroundColor: BLUE, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 8, justifyContent: 'center', alignItems: 'center' },
  discountCodeApplyText: { fontSize: 14, fontWeight: '700', color: WHITE },
  discountCodeError:    { fontSize: 12, color: CHERRY, marginTop: 4 },

  surchargeRow:          { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 12, backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: BORDER },
  surchargeRowName:      { fontSize: 14, fontWeight: '600', color: DARK },
  surchargeRowMeta:      { fontSize: 11, color: MUTED, marginTop: 2 },
  surchargeToggle:       { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  surchargeToggleActive: { backgroundColor: '#D1FAE5', borderColor: '#6EE7B7' },
  surchargeToggleText:   { fontSize: 12, fontWeight: '700', color: MID },
  surchargeToggleTextActive: { color: '#065F46' },
  surchargeChip:         { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  surchargeChipActive:   { backgroundColor: BLUE, borderColor: BLUE },
  surchargeChipText:     { fontSize: 13, fontWeight: '600', color: MID },
  surchargeNameInput:    { flex: 1, backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: BORDER, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: DARK },

  ticketNotesRow:   { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: WHITE, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  ticketNotesInput: { flex: 1, fontSize: 13, color: DARK, paddingVertical: 0 },

  holdOverlay:    { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  holdSheet:      { backgroundColor: WHITE, borderTopLeftRadius: 20, borderTopRightRadius: 20, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 12 },
  holdEmptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 10, paddingVertical: 48 },
  holdEmptyTitle: { fontSize: 16, fontWeight: '700', color: DARK },
  holdEmptyText:  { fontSize: 13, color: MUTED, textAlign: 'center', paddingHorizontal: 32 },
  holdRow:        { flexDirection: 'row', alignItems: 'flex-start', gap: 12, backgroundColor: '#FAFBFF', borderRadius: 12, padding: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: BORDER },
  holdRowIcon:    { width: 36, height: 36, borderRadius: 10, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center', flexShrink: 0 },
  holdRowCustomer: { fontSize: 13, fontWeight: '700', color: DARK },
  holdRowMeta:    { fontSize: 12, color: MUTED },
  holdRowItems:   { fontSize: 13, color: MID, lineHeight: 18 },
  holdRowNote:    { fontSize: 12, color: BLUE, marginTop: 3, fontStyle: 'italic' },
  holdRowTotal:   { fontSize: 15, fontWeight: '800', color: DARK },
  holdRowDelete:  { padding: 4 },

  settingsOverlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  settingsSheet:         { backgroundColor: WHITE, borderTopLeftRadius: 20, borderTopRightRadius: 20, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 12 },
  settingsSectionTitle:  { fontSize: 15, fontWeight: '700', color: DARK, marginBottom: 4 },
  settingsSectionDesc:   { fontSize: 13, color: MUTED, lineHeight: 18 },
  settingsPresetChip:    { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#F1F5F9', borderRadius: 20, borderWidth: 1, borderColor: BORDER },
  settingsPresetText:    { fontSize: 14, fontWeight: '700', color: DARK },
  settingsAddRow:        { flexDirection: 'row', alignItems: 'center', gap: 8 },
  settingsAddInput:      { width: 70, backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: BORDER, paddingHorizontal: 12, paddingVertical: 10, fontSize: 15, fontWeight: '700', color: DARK, textAlign: 'center' },
  settingsAddBtn:        { backgroundColor: BLUE, borderRadius: 10, paddingHorizontal: 18, paddingVertical: 10 },
  settingsAddBtnText:    { fontSize: 14, fontWeight: '700', color: WHITE },

  cpOverlay:    { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', alignItems: 'center' },
  cpSheet:      { backgroundColor: WHITE, borderRadius: 20, padding: 20, width: 280, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 10 },
  cpTitle:      { fontSize: 14, color: MID, marginBottom: 16, textAlign: 'center' },
  cpGrid:       { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center', marginBottom: 16 },
  cpSwatch:     { width: 44, height: 44, borderRadius: 12, borderWidth: 2, borderColor: 'transparent' },
  cpSwatchActive: { borderColor: DARK, transform: [{ scale: 1.1 }] },
  cpReset:      { alignItems: 'center', paddingVertical: 8 },
  cpResetText:  { fontSize: 13, color: MUTED, fontWeight: '600' },

  offlineBadge:           { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#D97706', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
  offlineBadgeText:       { fontSize: 11, fontWeight: '700', color: WHITE },

  syncToast:              { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#16A34A', paddingVertical: 10, paddingHorizontal: 16 },
  syncToastText:          { fontSize: 13, fontWeight: '700', color: WHITE },

  scannerBanner:          { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#16A34A', paddingVertical: 8, paddingHorizontal: 16, zIndex: 99 },
  scannerBannerError:     { backgroundColor: CHERRY },
  scannerBannerText:      { fontSize: 13, fontWeight: '700', color: WHITE, flex: 1 },

  offlinePayNotice:       { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#FEF3C7', borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#FCD34D' },
  offlinePayNoticeText:   { flex: 1, fontSize: 13, color: '#92400E', lineHeight: 18 },

  methodBtnDisabled:      { opacity: 0.4 },

  offlineCacheNotice:     { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FEF3C7', paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#FCD34D' },
  offlineCacheNoticeText: { fontSize: 12, color: '#92400E', fontWeight: '600' },

  failedSyncSection:      { backgroundColor: '#FFF1F2', margin: 12, marginBottom: 0, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#FECDD3' },
  failedSyncHeader:       { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  failedSyncTitle:        { fontSize: 14, fontWeight: '700', color: CHERRY },
  failedSyncSubtitle:     { fontSize: 12, color: '#9F1239', marginBottom: 10 },
  failedSyncRow:          { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#FECDD3' },
  failedSyncItems:        { fontSize: 13, fontWeight: '600', color: DARK },
  failedSyncMeta:         { fontSize: 12, color: MID, marginTop: 2 },
  failedSyncRetryBtn:     { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: BLUE },
  failedSyncRetryText:    { fontSize: 12, fontWeight: '700', color: WHITE },
  failedSyncDismissBtn:   { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: BORDER },
  failedSyncDismissText:  { fontSize: 12, fontWeight: '700', color: MID },

  pinOverlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  pinSheet:         { backgroundColor: WHITE, borderRadius: 24, width: '100%', maxWidth: 360, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 24, shadowOffset: { width: 0, height: 8 }, elevation: 12, overflow: 'hidden' },
  pinHeader:        { alignItems: 'center', paddingTop: 28, paddingBottom: 16, paddingHorizontal: 20 },
  pinLockCircle:    { width: 56, height: 56, borderRadius: 28, backgroundColor: `${BLUE}15`, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  pinTitle:         { fontSize: 18, fontWeight: '800', color: DARK, marginBottom: 6 },
  pinSub:           { fontSize: 13, color: MUTED, textAlign: 'center', lineHeight: 18 },
  pinDotsRow:       { flexDirection: 'row', justifyContent: 'center', gap: 14, marginVertical: 20 },
  pinDot:           { width: 16, height: 16, borderRadius: 8, borderWidth: 2, borderColor: BORDER, backgroundColor: WHITE },
  pinDotFilled:     { backgroundColor: BLUE, borderColor: BLUE },
  pinError:         { fontSize: 13, color: CHERRY, textAlign: 'center', marginBottom: 8, marginHorizontal: 20 },
  pinNumpad:        { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 20, gap: 10, justifyContent: 'center', marginBottom: 8 },
  pinKey:           { width: 80, height: 56, borderRadius: 14, backgroundColor: '#F1F5F9', justifyContent: 'center', alignItems: 'center' },
  pinKeyPressed:    { backgroundColor: `${BLUE}20` },
  pinKeyPlaceholder:{ width: 80, height: 56 },
  pinKeyText:       { fontSize: 22, fontWeight: '600', color: DARK },
  pinBackText:      { fontSize: 20, color: MID },
  pinCancel:        { alignItems: 'center', paddingVertical: 16 },
  pinCancelText:    { fontSize: 15, color: MUTED, fontWeight: '600' },

  ticketItemPriceStrike: { fontSize: 11, color: MUTED, textDecorationLine: 'line-through', textAlign: 'right' },

  priceEditSheet:       { backgroundColor: WHITE, borderRadius: 20, width: '100%', maxWidth: 340, padding: 24, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, shadowOffset: { width: 0, height: 6 }, elevation: 10 },
  priceEditTitle:       { fontSize: 17, fontWeight: '800', color: DARK, textAlign: 'center', marginBottom: 4 },
  priceEditSub:         { fontSize: 13, color: MUTED, textAlign: 'center', marginBottom: 20 },
  priceEditInputRow:    { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: BLUE, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 10, backgroundColor: '#F8FAFF' },
  priceEditDollar:      { fontSize: 22, fontWeight: '700', color: DARK, marginRight: 4 },
  priceEditInput:       { flex: 1, fontSize: 28, fontWeight: '700', color: DARK, padding: 0 },
  priceEditOriginal:    { fontSize: 12, color: MUTED, textAlign: 'center', marginBottom: 4 },
  priceEditHint:        { fontSize: 11, color: MUTED, textAlign: 'center', marginBottom: 20, lineHeight: 16 },
  priceEditActions:     { flexDirection: 'row', gap: 10 },
  priceEditCancel:      { flex: 1, height: 46, borderRadius: 12, borderWidth: 1.5, borderColor: BORDER, justifyContent: 'center', alignItems: 'center' },
  priceEditCancelText:  { fontSize: 15, fontWeight: '600', color: MID },
  priceEditConfirm:     { flex: 1, height: 46, borderRadius: 12, backgroundColor: BLUE, justifyContent: 'center', alignItems: 'center' },
  priceEditConfirmText: { fontSize: 15, fontWeight: '700', color: WHITE },

  voidSaleBtn:          { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, marginTop: 8, paddingVertical: 8, borderRadius: 8 },
  voidSaleBtnText:      { fontSize: 13, fontWeight: '600', color: MUTED },

  voidOverlay:          { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  voidSheet:            { backgroundColor: WHITE, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 20, paddingBottom: 32, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 16, shadowOffset: { width: 0, height: -4 }, elevation: 10 },
  voidHandle:           { width: 40, height: 4, borderRadius: 2, backgroundColor: BORDER, alignSelf: 'center', marginTop: 12, marginBottom: 20 },
  voidHeader:           { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  voidIconBg:           { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFF1F2', justifyContent: 'center', alignItems: 'center' },
  voidTitle:            { fontSize: 20, fontWeight: '800', color: DARK },
  voidSection:          { backgroundColor: '#F8FAFC', borderRadius: 14, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: BORDER },
  voidSectionLabel:     { fontSize: 10, fontWeight: '800', color: MUTED, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 10 },
  voidItemsList:        { gap: 6, marginBottom: 10 },
  voidItemRow:          { flexDirection: 'row', alignItems: 'center', gap: 6 },
  voidItemQty:          { fontSize: 13, fontWeight: '700', color: MID, width: 24 },
  voidItemName:         { flex: 1, fontSize: 13, color: DARK, fontWeight: '500' },
  voidItemPrice:        { fontSize: 13, fontWeight: '700', color: DARK },
  voidTotalRow:         { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER, marginBottom: 10 },
  voidTotalLabel:       { fontSize: 14, fontWeight: '600', color: MID },
  voidTotalValue:       { fontSize: 16, fontWeight: '800', color: DARK },
  voidPinNote:          { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FFFBEB', borderRadius: 8, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: '#FDE68A' },
  voidPinNoteText:      { fontSize: 12, color: '#92400E', fontWeight: '500', flex: 1 },
  voidConfirmBtn:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: CHERRY, borderRadius: 12, paddingVertical: 14 },
  voidConfirmBtnText:   { fontSize: 15, fontWeight: '800', color: WHITE },
  voidLastNote:         { fontSize: 13, color: MUTED, marginBottom: 10, lineHeight: 18 },
  voidLastBtn:          { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 12, paddingVertical: 13, borderWidth: 1.5, borderColor: '#FECDD3', backgroundColor: '#FFF1F2' },
  voidLastBtnText:      { fontSize: 15, fontWeight: '700', color: CHERRY },
  voidEmpty:            { alignItems: 'center', paddingVertical: 28, gap: 10 },
  voidEmptyText:        { fontSize: 14, color: MUTED, textAlign: 'center' },
  voidCancelBtn:        { alignItems: 'center', paddingVertical: 14, marginTop: 4 },
  voidCancelText:       { fontSize: 15, fontWeight: '600', color: MUTED },

  catActionSheet:       { backgroundColor: WHITE, borderRadius: 20, padding: 20, width: 260, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 10 },
  catActionTitle:       { fontSize: 15, fontWeight: '700', color: DARK, textAlign: 'center', marginBottom: 16 },
  catActionBtn:         { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, paddingHorizontal: 4 },
  catActionBtnText:     { fontSize: 15, fontWeight: '600' },
  catActionDivider:     { height: StyleSheet.hairlineWidth, backgroundColor: BORDER, marginVertical: 2 },
  catActionCancel:      { marginTop: 12, alignItems: 'center', paddingVertical: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: BORDER },
  catActionCancelText:  { fontSize: 15, fontWeight: '600', color: MUTED },

  reorderOverlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  reorderSheet:         { backgroundColor: WHITE, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: 32, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 12 },
  reorderHeader:        { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER },
  reorderTitle:         { fontSize: 17, fontWeight: '700', color: DARK, marginBottom: 2 },
  reorderSub:           { fontSize: 13, color: MUTED },
  reorderItem:          { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 20, height: REORDER_ITEM_H, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: BORDER, backgroundColor: WHITE },
  reorderItemDragging:  { backgroundColor: '#F0F7FF', shadowColor: BLUE, shadowOpacity: 0.15, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 6 },
  reorderColorDot:      { width: 12, height: 12, borderRadius: 6 },
  reorderItemText:      { flex: 1, fontSize: 15, fontWeight: '600', color: DARK },
  reorderHandle:        { padding: 10 },
  reorderFooter:        { flexDirection: 'row', gap: 10, paddingHorizontal: 20, paddingTop: 16 },
  reorderCancelBtn:     { flex: 1, alignItems: 'center', paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: BORDER },
  reorderCancelText:    { fontSize: 15, fontWeight: '600', color: MID },
  reorderSaveBtn:       { flex: 1, alignItems: 'center', paddingVertical: 14, borderRadius: 12, backgroundColor: BLUE },
  reorderSaveText:      { fontSize: 15, fontWeight: '700', color: WHITE },
});

export default styles;
