import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import loyaltyRouter from "./loyalty.js";
import staffRouter from "./staff.js";
import wholesaleRouter from "./wholesale.js";
import miscRouter from "./misc.js";
import paymentRouter from "./payment.js";
import addressesRouter from "./addresses.js";
import directorRouter from "./director.js";
import directorPricingRouter from "./director-pricing.js";
import directorCustomersRouter from "./director-customers.js";
import directorStoresRouter from "./director-stores.js";
import directorProductsRouter from "./director-products.js";
import storesRouter from "./stores.js";
import managerRouter from "./manager.js";
import storageRouter from "./storage.js";
import notificationsRouter from "./notifications.js";
import shopDisplayRouter from "./shop-display.js";
import stockRouter from "./stock.js";
import discountsRouter from "./discounts.js";
import adminSeedRouter from "./admin-seed.js";
import directorReportsExportRouter from "./director-reports-export.js";
import placesRouter from "./places.js";
import invoicesRouter from "./invoices.js";
import posRouter from "./pos.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/products", productsRouter);
router.use("/orders", ordersRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/staff", staffRouter);
router.use("/wholesale", wholesaleRouter);
router.use("/payment", paymentRouter);
router.use("/addresses", addressesRouter);
router.use("/director", directorPricingRouter);
router.use("/director", directorCustomersRouter);
router.use("/director", directorStoresRouter);
router.use("/director", directorProductsRouter);
router.use("/director", directorReportsExportRouter);
router.use("/director", directorRouter);
router.use(storesRouter);
router.use("/manager", managerRouter);
router.use("/notifications", notificationsRouter);
router.use("/shop-display", shopDisplayRouter);
router.use("/stock", stockRouter);
router.use("/discounts", discountsRouter);
router.use(storageRouter);
router.use("/places", placesRouter);
router.use("/invoices", invoicesRouter);
router.use("/pos", posRouter);
router.use(adminSeedRouter);
router.use(miscRouter);

export default router;
