// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/checkout-redesign/Direct.tsx": () => import("../components/mockups/checkout-redesign/Direct.tsx"),
  "./components/mockups/checkout-redesign/Express.tsx": () => import("../components/mockups/checkout-redesign/Express.tsx")
};
