// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/director-hub-redesign/AppOrders.tsx": () => import("../components/mockups/director-hub-redesign/AppOrders.tsx"),
  "./components/mockups/director-hub-redesign/PosTerminal.tsx": () => import("../components/mockups/director-hub-redesign/PosTerminal.tsx"),
  "./components/mockups/director-hub-redesign/Wholesale.tsx": () => import("../components/mockups/director-hub-redesign/Wholesale.tsx"),
  "./components/mockups/checkout-redesign/Direct.tsx": () => import("../components/mockups/checkout-redesign/Direct.tsx"),
  "./components/mockups/checkout-redesign/Express.tsx": () => import("../components/mockups/checkout-redesign/Express.tsx"),
  "./components/mockups/director-orders-current/CurrentAppOrders.tsx": () => import("../components/mockups/director-orders-current/CurrentAppOrders.tsx"),
  "./components/mockups/director-orders-current/CurrentPosTerminal.tsx": () => import("../components/mockups/director-orders-current/CurrentPosTerminal.tsx"),
  "./components/mockups/director-orders-current/CurrentWholesale.tsx": () => import("../components/mockups/director-orders-current/CurrentWholesale.tsx")
};
