const { withDangerousMod, withXcodeProject } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SHIM_FILENAME = 'StarIOSafeInit.m';

/**
 * Objective-C swizzle shim injected into POS iOS builds.
 *
 * react-native-star-io10 v1.12.x is eagerly initialised by React Native's
 * TurboModule registry at launch — before any JavaScript runs. On iOS 26 with
 * arm64e (Pointer Authentication Codes), the Star IO SDK throws an NSException
 * during this init (Bluetooth / LAN discovery API changes in iOS 26), which
 * causes React Native to call convertNSExceptionToJSError. At that point the
 * Hermes JSI runtime pointer fails PAC validation → SIGSEGV crash.
 *
 * This shim uses +load (guaranteed to run before any code in the binary) to:
 *   1. Swizzle -[StarIO10ReactNative init] and wrap it in @try/@catch.
 *   2. If init throws, set a static starIOInitFailed flag and use
 *      class_copyMethodList to replace EVERY instance method of
 *      StarIO10ReactNative with a safe no-op IMP. This prevents
 *      performVoidMethodInvocation from throwing when RN calls void methods
 *      on the partially-initialised instance — the real crash site on iOS 26.
 *
 * Consumer builds do not link StarIO10 at all (withPodfileExclusion plugin),
 * so this shim is only active in POS builds. NSClassFromString returns nil for
 * absent classes, making it a safe no-op on any build without the SDK.
 */
// Validated against: react-native-star-io10 ^1.12.1 (Star Micronics StarXpand SDK 1.12.x)
// Minimum tested iOS: 26.0 (arm64e / Pointer Authentication Codes)
// iOS compatibility matrix:
//   iOS 26  — shim required; SDK throws NSException in TurboModule eager init (PAC/arm64e)
//   iOS 17–25 — shim is a no-op (SDK inits cleanly); safe to leave in place
//   iOS <17  — untested; treat as unsupported for POS hardware
//
// When Star Micronics ships a new SDK version, verify the crash is still suppressed on
// the latest iOS beta before bumping the version pin in package.json. Update the
// "Validated against" line above and the STAR_IO_MIN_VERSION comment in eas.json.
const SHIM_CONTENT = `//
// StarIOSafeInit.m
// Auto-generated by withStarIOLazyInit Expo config plugin.
// DO NOT EDIT — regenerated on every expo prebuild.
//
// Validated against: react-native-star-io10 ^1.12.1 (Star Micronics StarXpand SDK 1.12.x)
// iOS compatibility: iOS 26 arm64e crash fix — see plugins/withStarIOLazyInit.js header.
//
// POS build safety net: suppresses iOS 26 / arm64e startup crash caused by
// react-native-star-io10 throwing an NSException during TurboModule eager
// initialisation, AND prevents performVoidMethodInvocation from crashing on
// any subsequently-invoked method of a partially-initialised StarIO instance.
//
#import <Foundation/Foundation.h>
#import <objc/runtime.h>

// Set to YES the first time StarIO10ReactNative -init throws. While this flag
// is set, every instance method on the class returns a safe no-op IMP so that
// performVoidMethodInvocation (called by RN after init) cannot re-throw.
static BOOL starIOInitFailed = NO;

// Universal no-op IMP returned for all void methods when init failed.
// id return type covers both void and id-returning selectors safely.
static id starIONoopIMP(id self, SEL _cmd) {
  return nil;
}

@interface StarIOSafeInitSwizzler : NSObject
@end

@implementation StarIOSafeInitSwizzler

/**
 * Replaces every instance method on cls with a no-op IMP.
 * Called once after a failed init so that any subsequent RN TurboModule
 * method dispatch (performVoidMethodInvocation, etc.) cannot throw.
 */
+ (void)replaceAllMethodsOnClass:(Class)cls withNoopIMP:(IMP)noopIMP {
  @try {
    unsigned int methodCount = 0;
    Method *methods = class_copyMethodList(cls, &methodCount);
    if (!methods) {
      return;
    }
    for (unsigned int i = 0; i < methodCount; i++) {
      Method m = methods[i];
      // Preserve -init itself (already swizzled) to avoid an infinite replace
      // loop; for every other method, inject the universal no-op.
      SEL sel = method_getName(m);
      if (sel_isEqual(sel, @selector(init))) {
        continue;
      }
      method_setImplementation(m, noopIMP);
    }
    free(methods);
    NSLog(@"[StarIOSafeInit] Replaced %u StarIO10 instance methods with no-op IMPs.", methodCount);
  } @catch (...) {
    // Never let the safety shim crash the app.
  }
}

+ (void)load {
  @try {
    // Resolve the Star IO TurboModule class at runtime so this shim compiles
    // even when the SDK is absent (e.g. non-POS simulator builds).
    Class cls = NSClassFromString(@"StarIO10ReactNative");
    if (!cls) {
      return;
    }

    SEL sel = @selector(init);
    Method originalMethod = class_getInstanceMethod(cls, sel);
    if (!originalMethod) {
      return;
    }

    IMP originalIMP = method_getImplementation(originalMethod);
    IMP universalNoopIMP = (IMP)starIONoopIMP;

    // Replace -init with a version that:
    //   a) Catches any NSException thrown during SDK initialisation on iOS 26.
    //   b) On failure, sets starIOInitFailed and replaces ALL instance methods
    //      with no-op IMPs so performVoidMethodInvocation cannot re-throw.
    IMP safeIMP = imp_implementationWithBlock(^id _Nullable (id _Nonnull self) {
      if (starIOInitFailed) {
        // A previous init already failed; return self without re-running init.
        return self;
      }
      @try {
        typedef id (*InitFunc)(id, SEL);
        InitFunc fn = (InitFunc)originalIMP;
        id result = fn(self, sel);
        return result;
      } @catch (NSException *exception) {
        NSLog(@"[StarIOSafeInit] Suppressed NSException from StarIO10 init on iOS 26: %@", exception.reason);
        // Mark all methods as no-ops BEFORE returning, so RN's subsequent
        // performVoidMethodInvocation calls land on the universal no-op.
        starIOInitFailed = YES;
        [StarIOSafeInitSwizzler replaceAllMethodsOnClass:[self class] withNoopIMP:universalNoopIMP];
        // Return self so callers get a valid (but non-functional) object.
        // The JS layer's dynamic import guard handles the unavailable module.
        return self;
      }
    });

    method_setImplementation(originalMethod, safeIMP);
    NSLog(@"[StarIOSafeInit] StarIO10 init swizzled for iOS 26 safety (full method no-op on failure).");
  } @catch (...) {
    // Never let the safety shim itself crash the app.
  }
}

@end
`;

/**
 * Writes StarIOSafeInit.m into the Xcode project directory and registers it
 * as a compiled source file in the .xcodeproj so it is built into the binary.
 *
 * For consumer builds, StarIO10 is excluded at the pod level by
 * withPodfileExclusion. This shim therefore only runs in POS builds where
 * the SDK is linked. IS_POS_BUILD env is checked in withPodfileExclusion;
 * here we always inject the shim so POS builds get the iOS 26 safety net
 * even when IS_POS_BUILD is not set at plugin-evaluation time.
 */
module.exports = function withStarIOLazyInit(config) {
  // 1. Write the .m shim file into the iOS app source directory.
  config = withDangerousMod(config, [
    'ios',
    async (modConfig) => {
      const projectName = modConfig.modRequest.projectName ?? 'butterfield';
      const iosDir = modConfig.modRequest.platformProjectRoot;
      const appSrcDir = path.join(iosDir, projectName);

      if (!fs.existsSync(appSrcDir)) {
        console.warn('[withStarIOLazyInit] iOS app source dir not found:', appSrcDir);
        return modConfig;
      }

      const shimPath = path.join(appSrcDir, SHIM_FILENAME);
      fs.writeFileSync(shimPath, SHIM_CONTENT, 'utf8');
      console.log('[withStarIOLazyInit] Wrote', SHIM_FILENAME, 'to', shimPath);
      return modConfig;
    },
  ]);

  // 2. Register the .m file as a compiled source in the Xcode project.
  config = withXcodeProject(config, (modConfig) => {
    const xcodeProject = modConfig.modResults;
    const projectName = modConfig.modRequest.projectName ?? 'butterfield';
    const firstTarget = xcodeProject.getFirstTarget();
    const relPath = `${projectName}/${SHIM_FILENAME}`;

    // Avoid adding duplicates across repeated prebuild runs.
    const existingFiles = xcodeProject.pbxSourcesBuildPhaseObj(firstTarget.uuid);
    const alreadyAdded = Object.values(existingFiles || {}).some(
      (f) => typeof f === 'object' && f !== null && typeof (f).fileRef === 'string' &&
        (() => {
          try {
            const key = (f).fileRef;
            const fileObj = xcodeProject.pbxFileReferenceSection()[key];
            return fileObj && fileObj.path && fileObj.path.replace(/"/g, '').includes(SHIM_FILENAME);
          } catch { return false; }
        })(),
    );

    if (alreadyAdded) {
      return modConfig;
    }

    // Resolve the main app PBX group by UUID rather than by path string.
    // xcode@3.0.1's addSourceFile walks the path string to find the parent group,
    // but on a fresh EAS prebuild the group is keyed by UUID — not the project name —
    // so the path-based lookup returns null and crashes. We locate the group UUID
    // ourselves and pass it directly as the third argument. The file reference path
    // still needs to include the physical folder prefix ("Butterfield/..."), because
    // Expo's generated PBXGroup is virtual (name-only, no path property).
    const pbxGroups = xcodeProject.hash.project.objects['PBXGroup'] || {};
    let appGroupKey = null;
    for (const [key, group] of Object.entries(pbxGroups)) {
      if (key.endsWith('_comment')) continue;
      const groupName = (group.name || '').replace(/"/g, '');
      const groupPath = (group.path || '').replace(/"/g, '');
      if (groupName === projectName || groupPath === projectName) {
        appGroupKey = key;
        break;
      }
    }

    if (appGroupKey) {
      xcodeProject.addSourceFile(relPath, { target: firstTarget.uuid }, appGroupKey);
      console.log('[withStarIOLazyInit] Registered', relPath, 'in Xcode project (group:', appGroupKey, ').');
    } else {
      // Fail loudly instead of adding a bad root-level reference. A wrong path causes
      // a later Xcode compile failure that is much harder to diagnose.
      throw new Error(`[withStarIOLazyInit] Could not find PBXGroup for ${projectName}; refusing to register ${relPath} with an incorrect root-level path.`);
    }

    return modConfig;
  });

  return config;
};
