const { withDangerousMod, withXcodeProject } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SHIM_FILENAME = 'StarIOSafeInit.m';

/**
 * Objective-C swizzle shim injected into the iOS build.
 *
 * react-native-star-io10 v1.12.x is eagerly initialised by React Native's
 * TurboModule registry at launch — before any JavaScript runs. On iOS 26 with
 * arm64e (Pointer Authentication Codes), the Star IO SDK throws an NSException
 * during this init (Bluetooth / LAN discovery API changes in iOS 26), which
 * causes React Native to call convertNSExceptionToJSError. At that point the
 * Hermes JSI runtime pointer fails PAC validation → SIGSEGV crash.
 *
 * This shim uses +load (guaranteed to run before any code in the binary) to
 * swizzle -[StarIO10ReactNative init] and wrap the original implementation in
 * @try/@catch. If the SDK throws on iOS 26, we catch, log, and return the
 * partially-initialised instance. The JS dynamic import guard in lib/printer.ts
 * then handles the case where the module is unavailable at runtime.
 */
// Validated against: react-native-star-io10 ^1.12.1 (Star Micronics StarXpand SDK 1.12.x)
// Minimum tested iOS: 26.0 (arm64e / Pointer Authentication Codes)
// iOS compatibility matrix:
//   iOS 26  — shim required; SDK throws NSException in TurboModule eager init (PAC/arm64e)
//   iOS 17–25 — shim is a no-op (SDK inits cleanly); safe to leave in place
//   iOS <17  — untested; treat as unsupported for POS hardware
//
// When Star Micronics ships a new SDK version, verify the crash is still suppressed on
// the latest iOS beta before bumping the version pin in package.json. Update the
// "Validated against" line above and the STAR_IO_MIN_VERSION comment in eas.json.
const SHIM_CONTENT = `//
// StarIOSafeInit.m
// Auto-generated by withStarIOLazyInit Expo config plugin.
// DO NOT EDIT — regenerated on every expo prebuild.
//
// Validated against: react-native-star-io10 ^1.12.1 (Star Micronics StarXpand SDK 1.12.x)
// iOS compatibility: iOS 26 arm64e crash fix — see plugins/withStarIOLazyInit.js header.
//
// Prevents iOS 26 / arm64e startup crash caused by react-native-star-io10
// throwing an NSException during TurboModule eager initialisation.
//
#import <Foundation/Foundation.h>
#import <objc/runtime.h>

@interface StarIOSafeInitSwizzler : NSObject
@end

@implementation StarIOSafeInitSwizzler

+ (void)load {
  @try {
    // Resolve the Star IO TurboModule class at runtime so this shim compiles
    // even when the SDK is absent (e.g. non-POS simulator builds).
    Class cls = NSClassFromString(@"StarIO10ReactNative");
    if (!cls) {
      return;
    }

    SEL sel = @selector(init);
    Method originalMethod = class_getInstanceMethod(cls, sel);
    if (!originalMethod) {
      return;
    }

    IMP originalIMP = method_getImplementation(originalMethod);

    // Replace -init with a version that suppresses NSException on iOS 26.
    IMP safeIMP = imp_implementationWithBlock(^id _Nullable (id _Nonnull self) {
      @try {
        typedef id (*InitFunc)(id, SEL);
        InitFunc fn = (InitFunc)originalIMP;
        return fn(self, sel);
      } @catch (NSException *exception) {
        NSLog(@"[StarIOSafeInit] Suppressed NSException from StarIO10 init on iOS 26: %@", exception.reason);
        // Return self so callers get a valid (but non-functional) object.
        // The JS layer's dynamic import guard handles the unavailable module.
        return self;
      }
    });

    method_setImplementation(originalMethod, safeIMP);
    NSLog(@"[StarIOSafeInit] StarIO10 init swizzled for iOS 26 safety.");
  } @catch (...) {
    // Never let the safety shim itself crash the app.
  }
}

@end
`;

/**
 * Writes StarIOSafeInit.m into the Xcode project directory and registers it
 * as a compiled source file in the .xcodeproj so it is built into the binary.
 *
 * Set IS_POS_BUILD=1 in your EAS build profile environment to skip this shim
 * if you ever ship a dedicated POS IPA that always has full Star IO access.
 */
module.exports = function withStarIOLazyInit(config) {
  // Skip on POS builds that need full Star IO access from the start.
  if (process.env.IS_POS_BUILD === '1') {
    console.log('[withStarIOLazyInit] IS_POS_BUILD=1 — skipping StarIO safety shim.');
    return config;
  }

  // 1. Write the .m shim file into the iOS app source directory.
  config = withDangerousMod(config, [
    'ios',
    async (modConfig) => {
      const projectName = modConfig.modRequest.projectName ?? 'butterfield';
      const iosDir = modConfig.modRequest.platformProjectRoot;
      const appSrcDir = path.join(iosDir, projectName);

      if (!fs.existsSync(appSrcDir)) {
        console.warn('[withStarIOLazyInit] iOS app source dir not found:', appSrcDir);
        return modConfig;
      }

      const shimPath = path.join(appSrcDir, SHIM_FILENAME);
      fs.writeFileSync(shimPath, SHIM_CONTENT, 'utf8');
      console.log('[withStarIOLazyInit] Wrote', SHIM_FILENAME, 'to', shimPath);
      return modConfig;
    },
  ]);

  // 2. Register the .m file as a compiled source in the Xcode project.
  config = withXcodeProject(config, (modConfig) => {
    const xcodeProject = modConfig.modResults;
    const projectName = modConfig.modRequest.projectName ?? 'butterfield';
    const firstTarget = xcodeProject.getFirstTarget();

    // Avoid adding duplicates across repeated prebuild runs.
    const existingFiles = xcodeProject.pbxSourcesBuildPhaseObj(firstTarget.uuid);
    const alreadyAdded = Object.values(existingFiles || {}).some(
      (f) => typeof f === 'object' && f !== null && typeof (f).fileRef === 'string' &&
        (() => {
          try {
            const key = (f).fileRef;
            const fileObj = xcodeProject.pbxFileReferenceSection()[key];
            return fileObj && fileObj.path && fileObj.path.replace(/"/g, '').includes(SHIM_FILENAME);
          } catch { return false; }
        })(),
    );

    if (alreadyAdded) {
      return modConfig;
    }

    // Resolve the main app PBX group by UUID rather than by path string.
    // xcode@3.0.1's addSourceFile walks the path string to find the parent group,
    // but on a fresh EAS prebuild the group is keyed by UUID — not the project name —
    // so the path-based lookup returns null and crashes. We locate the group UUID
    // ourselves and pass it directly as the third argument.
    const pbxGroups = xcodeProject.hash.project.objects['PBXGroup'] || {};
    let appGroupKey = null;
    for (const [key, group] of Object.entries(pbxGroups)) {
      if (key.endsWith('_comment')) continue;
      const groupName = (group.name || '').replace(/"/g, '');
      const groupPath = (group.path || '').replace(/"/g, '');
      if (groupName === projectName || groupPath === projectName) {
        appGroupKey = key;
        break;
      }
    }

    if (appGroupKey) {
      xcodeProject.addSourceFile(SHIM_FILENAME, { target: firstTarget.uuid }, appGroupKey);
      console.log('[withStarIOLazyInit] Registered', SHIM_FILENAME, 'in Xcode project (group:', appGroupKey, ').');
    } else {
      // Guard: if the group wasn't found, add without a group (goes to root group).
      // A misplaced file is better than a broken build.
      console.warn('[withStarIOLazyInit] Could not find PBXGroup for', projectName, '— adding', SHIM_FILENAME, 'to root group.');
      xcodeProject.addSourceFile(SHIM_FILENAME, { target: firstTarget.uuid });
    }

    return modConfig;
  });

  return config;
};
